# KFS-2: NASM + C -> our own linker script -> multiboot ELF -> bootable ISO. Build: make && make run

NAME      := kernel.bin
ISO       := kfs.iso

BUILD_DIR := build
ISO_DIR   := $(BUILD_DIR)/isodir

CC := gcc
AS := nasm
LD := ld

# Sources
ASM_SRCS := boot/boot.asm \
            boot/gdt_flush.asm
C_SRCS   := kernel/main.c \
            kernel/console.c \
            kernel/printk.c \
            kernel/gdt.c \
            kernel/stack.c \
            kernel/shell.c \
            drivers/vga.c \
            drivers/keyboard.c \
            lib/string.c

ASM_OBJS := $(ASM_SRCS:%.asm=$(BUILD_DIR)/%.o)
C_OBJS   := $(C_SRCS:%.c=$(BUILD_DIR)/%.o)
OBJS     := $(ASM_OBJS) $(C_OBJS)
DEPS     := $(C_OBJS:.o=.d)

# No libc or runtime; fixed address at 1 MB; ebp kept as a frame pointer for the stack printer;
# no SSE/MMX/x87 because SSE is off at boot (CR4.OSFXSR=0) and the first xmm instruction traps.
CFLAGS := -m32 -std=gnu99 -O2 \
          -ffreestanding -fno-builtin -fno-stack-protector \
          -fno-pie -fno-pic -nostdlib -nodefaultlibs \
          -fno-omit-frame-pointer -mgeneral-regs-only \
          -Wall -Wextra -Werror \
          -Iinclude -MMD -MP

ASFLAGS := -f elf32

# Our own linker script is used instead of the host's .ld file.
LDFLAGS := -m elf_i386 -T linker.ld -nostdlib

# Tool names differ per distribution (grub2-* on Fedora, grub-* on Debian).
GRUB_MKRESCUE := $(shell command -v grub2-mkrescue 2>/dev/null || command -v grub-mkrescue 2>/dev/null)
GRUB_FILE     := $(shell command -v grub2-file 2>/dev/null || command -v grub-file 2>/dev/null)
GRUB_I386_DIR := $(firstword $(wildcard /usr/lib/grub/i386-pc /usr/lib/grub2/i386-pc /usr/share/grub2/i386-pc))

# Keep the ISO small: BIOS target only, no fonts/locales/themes, only the modules we need.
# GRUB autoloads every partition-map module in its index, hence the part_* list.
GRUB_MODULES := multiboot normal biosdisk iso9660 \
                part_acorn part_amiga part_apple part_bsd part_dfly part_dvh \
                part_gpt part_msdos part_plan part_sun part_sunpc
GRUB_FLAGS := --fonts= --locales= --themes= --compress=xz \
              --install-modules="$(GRUB_MODULES)"
ifneq ($(GRUB_I386_DIR),)
GRUB_FLAGS += -d $(GRUB_I386_DIR)
endif

# -boot d makes the BIOS try the CD-ROM first; KVM=1 enables hardware acceleration.
QEMU  := qemu-system-i386
QEMUFLAGS := -cdrom $(ISO) -boot d -m 64
ifeq ($(KVM),1)
QEMUFLAGS += -enable-kvm
endif

.PHONY: all iso run clean fclean re check

all: $(ISO)

# --- Compilation rules ---
$(BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

$(BUILD_DIR)/%.o: %.asm
	@mkdir -p $(dir $@)
	$(AS) $(ASFLAGS) $< -o $@

# --- Link: every object into a single multiboot ELF ---
$(ISO_DIR)/boot/$(NAME): $(OBJS) linker.ld
	@mkdir -p $(dir $@)
	$(LD) $(LDFLAGS) -o $@ $(OBJS)
	@echo "==> linked $(NAME)"

# --- ISO: puts GRUB and the kernel together into a bootable image ---
$(ISO): $(ISO_DIR)/boot/$(NAME) grub/grub.cfg
	@if [ -z "$(GRUB_MKRESCUE)" ]; then \
		echo "ERROR: grub-mkrescue not found (Fedora: dnf install grub2-tools-extra xorriso)."; \
		exit 1; \
	fi
	@mkdir -p $(ISO_DIR)/boot/grub
	cp grub/grub.cfg $(ISO_DIR)/boot/grub/grub.cfg
	$(GRUB_MKRESCUE) $(GRUB_FLAGS) -o $(ISO) $(ISO_DIR)
	@echo "==> $(ISO) ready ($$(du -h $(ISO) | cut -f1))"

iso: $(ISO)

# Is the kernel really multiboot compliant and the ISO within the 10 MB limit?
check: $(ISO)
	$(GRUB_FILE) --is-x86-multiboot $(ISO_DIR)/boot/$(NAME) && echo "multiboot: OK"
	@test $$(stat -c %s $(ISO)) -lt 10485760 && echo "size: under 10 MB OK"

run: $(ISO)
	$(QEMU) $(QEMUFLAGS) -monitor stdio

clean:
	rm -rf $(BUILD_DIR)

fclean: clean
	rm -f $(ISO)

re: fclean all

# Header dependencies (generated by -MMD): a changed header rebuilds its .c
-include $(DEPS)
